export const CATEGORY_ADD_SUCCESS_ACTION = "CATEGORY_ADDED_SUCCESS";
export const CATEGORY_UPDATE_SUCCESS_ACTION = "CATEGORY_UPDATE_SUCCESS";
export const CATEGORY_UPDATE_FAILED_ACTION = "CATEGORY_UPDATE_FAILED";
export const CATEGORY_ADD_FAILED_ACTION = "CATEGORY_ADDED_FAILED";
export const CATEGORY_LIST_SUCCESS_ACTION = "CATEGORY_LISTED_SUCCESS";
export const CATEGORY_LIST_FAILED_ACTION = "CATEGORY_LISTED_FAILED";
export const CATEGORY_DELETE_SUCCESS_ACTION = "CATEGORY_DELETE_SUCCESS_ACTION";
export const CATEGORY_DELETE_FAILED_ACTION = "CATEGORY_DELETE_FAILED_ACTION";