export const COMMENT_ADD_SUCCESS_ACTION = "COMMENT_ADDED_SUCCESS";
export const COMMENT_UPDATE_SUCCESS_ACTION = "COMMENT_UPDATE_SUCCESS";
export const COMMENT_UPDATE_FAILED_ACTION = "COMMENT_UPDATE_FAILED";
export const COMMENT_ADD_FAILED_ACTION = "COMMENT_ADDED_FAILED";
export const COMMENT_LIST_SUCCESS_ACTION = "COMMENT_LISTED_SUCCESS";
export const COMMENT_LIST_FAILED_ACTION = "COMMENT_LISTED_FAILED";
export const COMMENT_DELETE_SUCCESS_ACTION = "COMMENT_DELETED_SUCCESS";
export const COMMENT_DELETE_FAILED_ACTION = "COMMENT_DELETED_FAILED";