export const HEADER_ADD_SUCCESS_ACTION = "HEADER_ADDED_SUCCESS";
export const HEADER_UPDATE_SUCCESS_ACTION = "HEADER_UPDATE_SUCCESS";
export const HEADER_UPDATE_FAILED_ACTION = "HEADER_UPDATE_FAILED";
export const HEADER_ADD_FAILED_ACTION = "HEADER_ADDED_FAILED";
export const HEADER_LIST_SUCCESS_ACTION = "HEADER_LISTED_SUCCESS";
export const HEADER_LIST_FAILED_ACTION = "HEADER_LISTED_FAILED";
export const HEADER_DELETE_SUCCESS_ACTION = "HEADER_DELETED_SUCCESS";
export const HEADER_DELETE_FAILED_ACTION = "HEADER_DELETED_FAILED";