export const PRODUCT_ADD_SUCCESS_ACTION = "PRODUCT_ADDED_SUCCESS";
export const PRODUCT_UPDATE_SUCCESS_ACTION = "PRODUCT_UPDATE_SUCCESS";
export const PRODUCT_UPDATE_FAILED_ACTION = "PRODUCT_UPDATE_FAILED";
export const PRODUCT_ADD_FAILED_ACTION = "PRODUCT_ADDED_FAILED";
export const PRODUCT_LIST_SUCCESS_ACTION = "PRODUCT_LISTED_SUCCESS";
export const PRODUCT_LIST_FAILED_ACTION = "PRODUCT_LISTED_FAILED";
export const PRODUCT_DELETE_SUCCESS_ACTION = "PRODUCT_DELETED_SUCCESS";
export const PRODUCT_DELETE_FAILED_ACTION = "PRODUCT_DELETED_FAILED";