export const PROJECT_ADD_SUCCESS_ACTION = "PROJECT_ADDED_SUCCESS";
export const PROJECT_UPDATE_SUCCESS_ACTION = "PROJECT_UPDATE_SUCCESS";
export const PROJECT_UPDATE_FAILED_ACTION = "PROJECT_UPDATE_FAILED";
export const PROJECT_ADD_FAILED_ACTION = "PROJECT_ADDED_FAILED";
export const PROJECT_LIST_SUCCESS_ACTION = "PROJECT_LISTED_SUCCESS";
export const PROJECT_LIST_FAILED_ACTION = "PROJECT_LISTED_FAILED";
export const PROJECT_DELETE_SUCCESS_ACTION = "PROJECT_DELETED_SUCCESS";
export const PROJECT_DELETE_FAILED_ACTION = "PROJECT_DELETED_FAILED";