export const ROLE_ADD_SUCCESS_ACTION = "ROLE_ADDED_SUCCESS";
export const ROLE_UPDATE_SUCCESS_ACTION = "ROLE_UPDATE_SUCCESS";
export const ROLE_UPDATE_FAILED_ACTION = "ROLE_UPDATE_FAILED";
export const ROLE_ADD_FAILED_ACTION = "ROLE_ADDED_FAILED";
export const ROLE_LIST_SUCCESS_ACTION = "ROLE_LISTED_SUCCESS";
export const ROLE_LIST_FAILED_ACTION = "ROLE_LISTED_FAILED";
export const ROLE_DELETE_SUCCESS_ACTION = "ROLE_DELETED_SUCCESS";
export const ROLE_DELETE_FAILED_ACTION = "ROLE_DELETED_FAILED";